site_name: PBWC
site_author: Dean Turpin
theme:
    name: readthedocs

nav:
    - PBWC: index.md
    - Ethusiast resources: collector.md
    - On the bench: repairs.md
    - Complete builds: complete.md

