site_name: PBWC
site_author: Dean Turpin
theme:
    name: readthedocs

nav:
    - PBWC: index.md
    - Watchmakers: watchmaker.md
    - Collectors: collector.md
    - repairs.md
    - Complete: complete.md
    - Reviews: reviews.md

