site_name: "The Brighton Watch"
site_description: "superdean.com - Horology and Watchmaking"
site_url: "https://superdean.com"

theme:
  name: material
  palette:
    - scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - content.code.copy

nav:
  - Home: index.md
  - Current Builds: builds.md
  - Completed Builds: complete.md
  - For Collectors: collector.md
  - Advanced Techniques: watchmaker.md
  - Tools: tools.md
  - Reviews: reviews.md
  - Marriage Watches: marriage.md
  - Molniya Special: molniya.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - tables

plugins:
  - search
  - glightbox

extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://superdean.com